<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?= $this->getHeadTitle() ?></title>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="/js/popper.min.js"></script>
    </head>
    <body>
        
        <div class="container">
            <header><h1>Second layout</h1></header>
        </div>
        
            
        
        <div class="container">
            <?php $this->template() ?>
        </div>
        
        
        <footer class="footer">
            <hr>
            <div class="container">
                <h4>Footer</h4>
            </div>
        </footer>
    </body>
</html>
