<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?= $this->getHeadTitle() ?></title>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/flatly-bootstrap.min.css">
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="/js/popper.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <div class="container">

                <a class="navbar-brand" href="/">SiteName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor03">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item <?= ($this->getHeadTitle() === 'Articles') ? 'active' : ''; ?>">
                      <a class="nav-link" href="/articles">Articles</a>
                    </li>  
                    <li class="nav-item 
                        <?php
                            if ($this->getHeadTitle() === 'Admin area' || $this->getHeadTitle() === 'Manage articles') {
                                echo 'active';
                            }
                        ?>
                        ">
                      <a class="nav-link" href="/admin">Admin area</a>
                    </li>
                  </ul>                
                </div>

            </div>
        </nav>
        <div class="container">
            <?php $this->template() ?>
        </div>
        
        <footer class="footer">
            <hr>
            <div class="container">
                <h4>Footer</h4>
            </div>
        </footer>
    </body>
</html>
