<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>
    <body>
        <?php foreach ($articles as $article) : ?>
        <div>
            <h3><?= $article->title; ?></h3>
            <div><?= $this->clearStr($article->short_content); ?></div>
            <div><?= $this->clearStr('<a href="#">Hello</a>'); ?></div>
            <div><?= "<a href='#'>Hello</a>" ?></div>
            <div><a href="/article/view/<?= $article->id ?>">Read more &Gt;</a></div>
        </div>
        <br>
        <br>
        <?php endforeach; ?>
    </body>
</html>
