<div>
    <?php foreach ($articles as $article) : ?>
    <div class="card">
        <div class="card-header">
            <img class="app-block-image img-fluid float-left"
                 src="<?= $this->clearStr($article->image); ?>" 
                 alt="<?= $this->clearStr($article->title); ?>"
             >
            <h4><?= $article->title; ?></h4>
        </div>

        <div class="card-body">
            <div><?= $this->clearStr($article->short_content); ?></div>
        </div>

        <div class="card-footer">
            <div><a href="/article/view/<?= $article->id ?>" class="card-link">Read more &Gt;</a></div>
        </div>
    </div>
    <br>
    <br>
    <?php endforeach; ?>
</div>
