<div class="row">
    <div class="col-sm-12">
       <h5><?= $this->clearStr($this->getHeadTitle()) ?></h5>
    </div>
</div>
<hr>
<br>
<div class="row">
    <div class="col-sm-10">
        <form action="/manage-articles/add" method="post" id="add-article-form" enctype="multipart/form-data">
            
            <div class="form-group row">
                <label class="control-label col-sm-2 asterisk" for="title">Title:</label> 
                <div class="col-sm-10">
                    <input id="title" type="text" name="title" class="form-control" required="">
                </div>
            </div>
            
            <div class="form-group row">
                <label class="control-label col-sm-2" for="short_content">Short content:</label>  
                <div class="col-sm-10">
                    <textarea id="short_content" name="short_content" class="form-control"></textarea>
                </div>
            </div>   
            
            <div class="form-group row">
                <label class="control-label col-sm-2 asterisk" for="content">Content:</label> 
                <div class="col-sm-10">
                    <textarea id="content" name="content" class="form-control" required=""></textarea>
                </div>
            </div>  
            
            <div class="form-group row">             
                <div class="col-sm-12 offset-sm-2"> 
                    <label class="custom-file">
                        <input type="file" name="file" id="file" class="custom-file-input">
                        <span class="custom-file-control"></span>
                    </label>
                </div>     
            </div>
            
            <div class="row">               
                <div class="col-sm-12 offset-sm-2">
                    <input type="submit" value="Submit" name="add_article">
                </div>
            </div>
            
        </form>
    </div>
</div>
<br>
<br>
<br>
