<div class="row">
    <div class="col-sm-12">
       <h5><?= $this->clearStr($this->getHeadTitle()) ?></h5>
    </div>
</div>
<hr>
<br>
<div class="row">
    <div class="col-sm-10">
        <form action="/manage-articles/edit/<?= $this->clearInt($article->id) ?>" method="post" id="edit-article-form" enctype="multipart/form-data">
            
            <div class="form-group row">
                <label class="control-label col-sm-2 asterisk" for="title">Title:</label> 
                <div class="col-sm-10">
                    <input id="title" 
                           type="text" 
                           name="title" 
                           class="form-control" 
                           value="<?= $this->clearStr($article->title) ?>"
                           required=""
                    >
                </div>
            </div>
            
            <div class="form-group row">
                <label class="control-label col-sm-2" for="short_content">Short content:</label>  
                <div class="col-sm-10">
                    <textarea id="short_content" name="short_content" class="form-control"><?= $this->clearStr($article->short_content) ?></textarea>
                </div>
            </div>   
            
            <div class="form-group row">
                <label class="control-label col-sm-2 asterisk" for="content">Content:</label> 
                <div class="col-sm-10">
                    <textarea id="content" name="content" class="form-control" required=""><?= $this->clearStr($article->content) ?></textarea>
                </div>
            </div> 
  
            <div class="form-group row">
               
                <div class="col-sm-12 offset-sm-2">
                    <img src="<?= $this->clearStr($article->image) ?>" alt="image" class="app-block-image img-fluid">
                </div>
            </div>  
            
            <div class="form-group row">             
                <div class="col-sm-12 offset-sm-2"> 
                    <label class="custom-file">
                        <input type="file" name="file" id="file" class="custom-file-input">
                        <span class="custom-file-control form-control-file"></span>
                    </label>
                </div>     
            </div>
            
            <div class="row">               
                <div class="col-sm-12 offset-sm-2">
                    <input type="submit" value="Submit" name="add_article">
                </div>
            </div>
            
        </form>
    </div>
</div>
<br>
<br>
<br>
